### ISSUE TITLE
Implement a Cairo struct to represent NIP-01 event

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#10]
https://github.com/nostr-protocol/nips/blob/master/01.md

**Comment by kateberryd** [comment]
Can you

**Comment by maciejka** [comment]
> @maciejka Can I work on this?

Hey, nice to meet you. How long do you think it would take you?

**Comment by kateberryd** [comment]
@maciejka It's nice to meet you too. this would take few working hours

**Comment by kateberryd** [comment]
@maciejka Please what's your telegram handle

**Comment by maciejka** [comment]
@Aundumla

**Comment by nicosanc** [comment]
I would like to work on this issue. I'm coming from ODHack. I'm a new Cairo developer but I'm confident I could tackle this issue in about 2-3 days. Let me know if this is still up for grabs!
