### ISSUE TITLE
Feed Screen Post Card re-design

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#102]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

Please read the guidelines and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Feed Screen Post Card re-design

Post card should be re-designed to match the new design. The new design is available at Figma: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=235-5345&t=QIIZCaGcwk8ziRaQ-0

Current Post card implementation can be found at: https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/shared/components/Post.tsx

You should implement the design as close as possible and should match 1:1 with or without an image. You should only implement the post card design, not the whole feed screen.

Please battle test it before doing a PR.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by bhavyagosai** [comment]
Hey

**Comment by josephchimebuka** [comment]
i would like to work on this

**Comment by ugur-eren** [comment]
Hi @bhavyagosai What's the status of this issue? If you can't continue we have to assign this to someone else before the OD Hack ends

**Comment by bhavyagosai** [comment]
Hey, sorry for the delay...I was a bit under the weather yesterday. Let me finish this up by tonight and raise a PR!
