### ISSUE TITLE
Post Creation page re-design

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#103]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

Please read the guidelines and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Post Creation page re-design

Post creation page should be re-designed to match the new design. The new design is available at Figma: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=235-6746&t=QIIZCaGcwk8ziRaQ-0

Current Post creation page implementation can be found at: https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/modules/post/index.tsx

You should implement the design as close as possible and should match 1:1.

Please battle test it before doing a PR.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by shivam6862** [comment]
ok

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by josephchimebuka** [comment]
I would to work on this

**Comment by ugur-eren** [comment]
@josephchimebuka how much time would it take you?

**Comment by josephchimebuka** [comment]
I can handle it in 3 working days
