### ISSUE TITLE
Implement a function to verify `NIP01Event` signature using `bip340`

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#11]
For verification use: https://github.com/keep-starknet-strange/joyboy/blob/4c572d060c946efb74b23f661a2576fe1cc1421f/onchain/src/bip340.cairo#L91
Depends on #10.

**Comment by EjembiEmmanuel** [comment]
@maciejka I'd love to be assigned to this

**Comment by maciejka** [comment]
> @maciejka I'd love to be assigned to this

Hey, nice to meet you. How long do you think it would take you?

**Comment by EjembiEmmanuel** [comment]
@maciejka probably a week or two

**Comment by maciejka** [comment]
> @maciejka probably a few working works

It is yours!

**Comment by EjembiEmmanuel** [comment]
@maciejka since the issue depends #10 do I need to wait for it to get completed?

**Comment by maciejka** [comment]
@EjembiEmmanuel Hey, this issue is blocked by #10 and #26. It makes sense to wait until both are ready.

**Comment by maciejka** [comment]
@EjembiEmmanuel this issue is unblocked. You should start here: https://github.com/keep-starknet-strange/joyboy/blob/b281209cd2d4ccf4ff772935e195bfdb0ed56f19/onchain/src/social/request.cairo#L19

**Comment by EjembiEmmanuel** [comment]
Alright.

**Comment by nicosanc** [comment]
I'd like an opportunity to work on this. I'm a new Cairo dev looking to get experience with a newcomer issue.
