### ISSUE TITLE
Channels Designs

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#116]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

Please read the guidelines and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Channels Designs

We're in the process of adding channels support to the app. We need a base design for these screens in order to start the development.

Required screens for the design are:
- Channels List
- Channel Feed
- Create new Channel

And any other screens you think are necessary.

@Israelrex9 I can assign this to you.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by Israelrex9** [comment]
Yes, I am open to it

**Comment by shivam6862** [comment]
Hi, I would like to work on the development phase of it, after it gets ready,
I am a frontend developer with a couple of years of experience

**Comment by Israelrex9** [comment]
Hi @ugur-eren 
I am done with this task here is the figma link and this is the design on figma

https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?m=dev&node-id=33-1450&t=VgPHUyXxjlORRrye-1

![Screenshot 2024-05-30 at 3 19 19 PM](https://github.com/keep-starknet-strange/joyboy/assets/46507005/7397b2d3-9f68-412b-9ce5-e2ae2447e40f)

**Comment by Israelrex9** [comment]
> @Israelrex9 do you need any assistance with it or something? I'm a designer too and would like to contribute to this.

Hi @Osatuyi 
At the moment, I don't think there are any more screens to design for the MVP and also I am still trying to get the theme right, hopefully on the next iterations you can join me.

Kindly dm me on telegram.

**Comment by ugur-eren** [comment]
Great work! As always, looks awesome!

**Comment by Osatuyi** [comment]
@Israelrex9 same username, yeah?

**Comment by Osatuyi** [comment]
> > @Israelrex9 do you need any assistance with it or something? I'm a designer too and would like to contribute to this.
> 
> Hi @Osatuyi 
> At the moment, I don't think there are any more screens to design for the MVP and also I am still trying to get the theme right, hopefully on the next iterations you can join me.
> 
> Kindly dm me on telegram.
> 


Same username, yeah?
