### ISSUE TITLE
Profile / Edit Profile Designs

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#117]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

Please read the guidelines and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Profile / Edit Profile Designs

We need to have a profile view and a profile edit screen to edit profile information. We need a base design for these screens in order to start the development.

Required screens for the design are:
- User's Profile
- Other users Profile
- Edit Profile

And any other screens you think are necessary.

@Israelrex9 I can assign this to you.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by NueloSE** [comment]
c

**Comment by raizo07** [comment]
@ugur-eren I'll like to work on this

**Comment by ugur-eren** [comment]
Hi @NueloSE  @raizo07 sorry, unfortunately @Israelrex already working on the app design and I would like to give this issue to him since he's already designed the most parts of the app.

**Comment by NueloSE** [comment]
@ugur-eren am open for any design or front-end issue if avaliable

**Comment by Israelrex9** [comment]
I will work on it, thank you @ugur-eren

**Comment by Israelrex9** [comment]
Here is the resolve to this issue
https://github.com/keep-starknet-strange/joyboy/discussions/51#discussioncomment-9564948

Here is the figma
https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?m=dev&node-id=33-1450&t=UW5TgfavpXKRZFFW-1

**Comment by ugur-eren** [comment]
@NueloSE we might have new issues in the coming days, will keep you notified if we will have new issues.

**Comment by ugur-eren** [comment]
Oh, thanks for the work @Israelrex9
