### ISSUE TITLE
Define the data structure for tip transactions.

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#12]

**Comment by Jemiiah** [comment]
can i work on this?

**Comment by MubarakCinderbuild** [comment]
@maciejka i will like to work on this,
kindly assign me and update the issue description

**Comment by mubarak23** [comment]
@maciejka i will like to work on this,
kindly assign me and update the issue description

**Comment by mubarak23** [comment]
@maciejka i will like to work on this,
kindly assign me and update the issue description

**Comment by Jemiiah** [comment]
@maciejka is this work assignable

**Comment by TEMHITHORPHE** [comment]
Why was this closed?, do we have a structure already?
