### ISSUE TITLE
Map nostr public key to DNS joyboy.community using NIP-05

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#13]
Map a sample public key to DNS: `joyboy.community` by using NIP-05 on
https://github.com/keep-starknet-strange/joyboy/tree/main/website.

See: https://github.com/nostr-protocol/nips/blob/master/05.md
Sample pubkey: `npub1nq5ckz62p4vxwu08lpx8ggu5k5qn6d7pdtcfyj7hae3wc6j30fwseex2rq`

Extended description:
We want the nostr.json to be returned on joyboy.community. 

The content of nostr.json needs to be dynamic, we want both:
* https://joyboy.community/.well-known/nostr.json?name=_
* https://joyboy.community/.well-known/nostr.json?name=testnet
 to work.

In order to nostr.json be dynamic we need to move from ReactApp to Next.js(unless you have better suggestions). In Next.js it should be possible to generate dynamic routes.

Please make sure the current content and design of index page is preserved.

**Comment by Gift-Naomi** [comment]
can i work on this please?

**Comment by maciejka** [comment]
> @maciejka can i work on this please?

Yes, please. How long do you think it will take you?

**Comment by Gift-Naomi** [comment]
Approximately, Two weeks.

**Comment by maciejka** [comment]
You mean that you think it will take 10 mandays to complete or that you will work on it from time to time over the next two weeks?

**Comment by Gift-Naomi** [comment]
That's like the max just incase i run into errors,but I'll get it done as soon as possible

**Comment by maciejka** [comment]
Ok. Go for it. FYI: I estimate it to be max 2h of work.

**Comment by Gift-Naomi** [comment]
Alright,  Thank you

**Comment by Josh-121** [comment]
I can work on this, can I be assigned?

**Comment by maciejka** [comment]
Done in pr #95, now waiting for vercel configuration reset.
