### ISSUE TITLE
Figma: Create design for profile tabs

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#138]
We need to have tabs on profile to view different posts on profile. We need a base design for this in order to start the development.

These tabs should be added to the profile:
- Posts
- Replies
- Reactions
- Reposts   

And any other tabs / screens you think are necessary.

@Israelrex9 I can assign this to you.

**Comment by Israelrex9** [comment]
okay, will work on it

**Comment by Osatuyi** [comment]
Please can I work on this?

**Comment by Israelrex9** [comment]
> Please can I work on this? @Israelrex9

Hi @Osatuyi this design page already exists, it needs some changes.
Kindly reply to me on telegram.

**Comment by Israelrex9** [comment]
I have included the tabs on the profile page @ugur-eren 

Figma; https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?m=dev&node-id=33-1450&t=7FutODVNtnowEwTh-1

![Screenshot 2024-06-01 at 7 36 37 AM](https://github.com/keep-starknet-strange/joyboy/assets/46507005/8a8ac538-d5ce-4a0f-916f-2254b1b5af7a)

**Comment by ugur-eren** [comment]
Thanks for the work, looks great!
