### ISSUE TITLE
Tipping screen

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#152]
Please read the [Contributors Guidelines](https://github.com/keep-starknet-strange/joyboy/blob/main/.github/CONTRIBUTING.md) and make sure you follow them.

Include the estimated delivery timeline (start date and estimated completion date), describe how you would approach this task and include  a brief summary of relevant skills on the comments.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Tipping screen

Tipping screen should be designed by following the Figma design. It should match the design 1:1. The design is available at Figma: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=235-6346&t=R1Eel6o2kJ8UMjbP-0

You can use the `Modalize` component to render the modal. It should be added to Post module.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by EjembiEmmanuel** [comment]
j

**Comment by Joy-Adah** [comment]
Can I be assigned this? It would take me approximately 2-3 days to complete.
