### ISSUE TITLE
Tipping success modal

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#153]
Please read the [Contributors Guidelines](https://github.com/keep-starknet-strange/joyboy/blob/main/.github/CONTRIBUTING.md) and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Tipping success modal

Tipping success modal should be designed by following the Figma design. It should match the design 1:1. The design is available at Figma: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=240-7803&t=R1Eel6o2kJ8UMjbP-0

Modal should be rendered within a Portal component to ensure it is rendered at the top of other components.
There are multiple stars in the design. They can be grouped with the Joyboy svg and rendered as a single svg.
You can use the Button component for the button.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by kateberryd** [comment]
I would

**Comment by EjembiEmmanuel** [comment]
@ugur-eren I'd love to work on this

**Comment by Immanuelolivia1** [comment]
Can I be assigned to this ?

**Comment by Joy-Adah** [comment]
Hi @ugur-eren can I be assigned this? I'll have it ready by Thursday.

**Comment by Osatuyi** [comment]
@ugur-eren  can I be assigned this? I'm a uiux designer. I can get this done within 3 days.

**Comment by rahulsingh3526** [comment]
guys can I work on this issue I can code the frontend pretty fast
