### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by ugur-eren** [keep-starknet-strange/joyboy#154]
Please read the [Contributors Guidelines](https://github.com/keep-starknet-strange/joyboy/blob/main/.github/CONTRIBUTING.md) and make sure you follow them.

**Please write your thoughts and how long you think it will take to complete the issue in the comments.**

### Toast component

We need to have a Toast component to show alerts to the user. The component should match the design 1:1. The design is available at Figma: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=461-8570&t=R1Eel6o2kJ8UMjbP-0

You should only design the component. No need to create a toast manager or anything like that. Just the component.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by ABerkeBora** [comment]
I would like to work on this issue as I’ve experience with React Native and already have projects up and running in web.

**Comment by addegbenga** [comment]
I would like to work on this as i have years of experience building mobile and webapps.
Estimated delivery timeline for this tasks will be 1 working day.
Approach:
I will carefully review the Figma design then will use the existing styling on the project to create a pixel perfect toast component that matches the design.

**Comment by ugur-eren** [comment]
Hi @addegbenga This task will be assigned on a first-come, first-served basis since it's a really small task. However we have 2 more issues available

**Comment by addegbenga** [comment]
> Hi @addegbenga This task will be assigned on a first-come, first-served basis since it's a really small task. However we have 2 more issues available

Okay thanks i will check and drop a comment
