### ISSUE TITLE
Draft SocialPay account contract, initialize it with Nostr private key(`Secp256k1Point`).

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#16]
Draft a very simple contract which will be a base of SocialPay account:
* it should have a single storage  slot - `public_key: Secp256kPoint` - to keep Nostr public key
* it should emit `AccountCreated { public_key }` event
* for now it should not have any other methods

**Comment by mubarak23** [comment]
@maciejka can you assigned this issue to me.
