### ISSUE TITLE
Punctuations, Grammatical errors and Mispelling

### ISSUE THREAD

**Issue by LawrenceEzealor** [keep-starknet-strange/joyboy#203]
[Under](url) Origin Story, I made the changes below

1. I changed "the character" to "a character" to align with the indefinite article usage
2. I added a period after "One piece" in the first sentence to correct the punctuation
3. I changed "are" to "is" in "the treasure are the friends" to ensure subject-verb agreement

4. I added a comma after "WalletCOnnect" to separate the clause
5. I changed "setup" to "set up" to use the correct verb form
6. I added "an" before "ordinary Starknet wallet" for grammatical correctness
7. I added a comma after Argent or Braavos to separate the two alternatives
8. I added "the" before "so-called SocialPay" for grammatical correctness
9. I capitalized BIP340 to standardize the abbreviation
10. I removed "one" after "Nostr native" to avoid redundancy
11. I changed "Bravvos" to "Braavos" because Bravvos is misleading as that isn's the correct spelling of the Braavos wallet.

Under Tips, i made the changes below

12. I added a colon after "React Native" to introduce what follows
13. I changed "on the first days" to "in the first days" for grammatical correctness
14. I added "are" before "welcome" for grammatical correctness

Below is the link to the updated
[https://github.com/keep-starknet-strange/joyboy/pull/207](https://github.com/keep-starknet-strange/joyboy/pull/207)

**Comment by od-hunter** [comment]
can i take on this issue @LawrenceEzealor

**Comment by mathstickz** [comment]
can i take on this issue @LawrenceEzealor
