### ISSUE TITLE
Claim does not disappear after a successful claim

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#208]
The first claim should disappear below:
![image](https://github.com/keep-starknet-strange/joyboy/assets/190855/1d367578-c65d-42a9-bb6e-adc86ec6a64e)

**Comment by EjembiEmmanuel** [comment]
@maciejka I'd love to work on this

**Comment by ugur-eren** [comment]
![resim](https://github.com/keep-starknet-strange/joyboy/assets/86152092/d0d86206-33ae-47ae-ad73-f9af5cf56e66)
