### ISSUE TITLE
Change title of  "Connect Wallet" to "Claim" 

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#209]
![image](https://github.com/keep-starknet-strange/joyboy/assets/190855/058ab377-836b-4685-91af-32c1ed5ec16f)

**Comment by adrianvrj** [comment]
Hi, can I work on this?

**Comment by mathstickz** [comment]
i would love to be a path of issue@https://github.com/maciejka

**Comment by ugur-eren** [comment]
> i would love to be a path of issue@https://github.com/maciejka

Hi, unfortunately this issue is already resolved.
