### ISSUE TITLE
Transaction progress modal is not up to date.

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#217]
I successfully sent a tip. Transaction progress modal does not seem to reflect this.
![image](https://github.com/user-attachments/assets/1d0e373a-4d31-4a51-a60b-e08c746296fd)
![image](https://github.com/user-attachments/assets/f8e77f66-a155-4590-b311-f4e39e069755)

**Comment by maciejka** [comment]
After a while, on another tip it seems to work:
![image](https://github.com/user-attachments/assets/f6474112-8869-4fdb-aaf8-1348968f03e2)

**Comment by mathstickz** [comment]
hmm maybe it is caused by an error in the code would love to rectify this @maciejka

**Comment by ugur-eren** [comment]
@mathstickz Unfortunately I've already resolved this.
