### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#223]
** Stay tuned for the announcement and the start of the Beta testing**

JM, join us the 19/07 on the Joyboy community call: https://github.com/keep-starknet-strange/joyboy/discussions/224

The beta testing contest is closing on Wednesday, 24/07. 

You need to send your report before the end date, as described in the next steps.

# How to test and help us 

The demo is live here: 
https://app.joyboy.community/ 

- You can request to be assigned to the GitHub issue.
- Send a Post (Note) on Joyboy with your GitHub ID (check this step to get your Github ID: https://t.me/JoyboyStarknet/1/2864

Come back later, and if you are assigned you can start the beta test: 
Let's write an issue or a doc with a description of what you did, as well as your Nostr profile and Starknet address.

# Submit Report

Here is the description to send your report:  

1. Report any problems you encounter in just a few steps: 
What the problem is, how to reproduce the steps, error logs, and messages that may help. 
You can open different issues for these (check if it's not already reported maybe)

2. Transaction hash for : 
- Giving a tip to a friend. 
- Initial claim (without funds, sent by payer) 
- Claim a deposit (sign the transaction with your wallet). 

3. Screens : 
Your GitHub ID comment is here in a comment, and on Joyboy. 
Edit profile screens with your sent notes and your profile on Joyboy.

# Onboard

Login/Sign

1. Create a Nostr account to login, in with a username and a password.

![image](https://github.com/user-attachments/assets/6cc3f3cb-7c44-43f5-a389-7077045261f4)

![image](https://github.com/user-attachments/assets/baf09cd5-92e7-455f-93b9-d3d6dce2d125)

2. Save your Private key of Nostr.

3. Go to the home page and visit the app (Feed of notes, your profile, others profiles)

![image](https://github.com/user-attachments/assets/343ccee5-cff1-4c46-b5f1-a851148705aa)

# Nostr

1. Send a note:
  - Send JM with your GitHub ID, and request a tip with some thoughts, ideas, or feedback about Joyboy
(check this step to get your Github ID: https://t.me/JoyboyStarknet/1/2864)

![image](https://github.com/user-attachments/assets/1d6e6125-560c-4246-86ca-6f4696457c37)

2. Comment a note/comment of another user
3. Give a reaction to a Note
4. Edit your profile
  - Click to the profile icon 
  - Add your Username and NIP-5
  
![image](https://github.com/user-attachments/assets/dc5e44c2-32bf-4839-95e8-4978869c302e)

# Tipping task

1. Create a Starknet Wallet in your Browser extension: Argent, Bravoos, OKX.

You can install one directly on Joyboy:

![image](https://github.com/user-attachments/assets/7dff4ed7-aa6c-4457-952d-ef0458d9f578)

Create your wallet
Save your Starknet private key somewhere

Request fun on Joyboy:
Send a note: JM please tips me.
One user or the team gonna send you a tip.

Come back a few moment later: 
Go to the claim page as described below and claim your first fund paid by the paymaster.

3. Login with your Wallet (Argent supported on Mobile, Bravoos OKX etc on Web view)
4. Send a tip to your friends

-  Click on the icon of a Notes or in a User profile

![image](https://github.com/user-attachments/assets/0a5a01bf-894d-4004-81d1-2d240d21009e)

- Click on Tips. Send the Token and the amount you want to used.

![image](https://github.com/user-attachments/assets/5c119440-c68b-4bfc-b0c2-e47355ed7d10)

- Connect your wallet

![image](https://github.com/user-attachments/assets/def8a436-cbfa-4182-a2a8-16c6be692840)

- Sign the transaction to tip your friends in your wallet. 

- Get confirmation of your tips is sent correctly

![image](https://github.com/user-attachments/assets/ed21b3db-3cd4-444f-bcc2-72d935f3849f)

![image](https://github.com/user-attachments/assets/4166541a-4516-4292-b113-6549dd058c66)

5. Claim your tips 

- Go to the Claim page (Click on the 2th button in the Bottom bar)

If you don't have tips, you can tip you or:
Request a tip on Joyboy:
Send a note: JM please tips me.
One user or the team gonna send you a tip.
Go to the claim a few moments after (we are reactive)

![image](https://github.com/user-attachments/assets/95697d3a-046f-4e93-a19d-f79225744fbd)

- Select a Tips to claim (if not yet done)
If you don't have tips to claim, send a tip directly to you, or request a tip in the Telegram or on X with your Nostr public key 

- Claim your tips
  - Click on the claim button.
 
How it work: 
- If you have some ETH or Starknet fund: you can sign the tx to claim your fund
- If no ETH fund, the paymaster claims it for you.
  
![image](https://github.com/user-attachments/assets/8bfd77cb-889b-4f45-a030-f55341db44d6)

  - Transaction hash succeed.
  
![image](https://github.com/user-attachments/assets/1e828a4c-a3e7-4703-bb29-390cef94ce8a)

  -  You see the label Claimed with a Disabled button

![image](https://github.com/user-attachments/assets/7b0060f4-c99f-4f71-8aaa-52df6ecbf7b6)

# Give your feedback and report the bug

Here is the description (present in the beta test issue) to send your report:  

1. Report any problems you encounter in just a few steps: 
What the problem is, how to reproduce the steps, error logs, and messages that may help. 
You can open differents issues for these (check if it's not already reported maybe)

2. Transaction hash for : 
- Giving a tip to a friend. 
- Initial claim (without funds, sent by payer) 
- Claim a deposit (sign the transaction with your wallet). 

3. Screens : 
Your GitHub ID comment is here in a comment, and on Joyboy. 
Edit profile screens with your sent notes and your profile on Joyboy.

Feedback:

What do you think, you want, you need. Let's discuss!

**Comment by MartinXV111** [comment]
JM, i'll love to be assigned to the issue!

**Comment by adrienlacombe** [comment]
J'y aime, I would like to participate as well :) ty ty

**Comment by Megumiiiiii** [comment]
JM! may I participate too?

**Comment by lauchaves** [comment]
Hey @MSghais, @maciejka ! 👋  

I'm Lau Chaves, I would like to contribute to this one!
I have over 5 years of experience working with js,react,ts...  I already played around with the demo a bit, looks awesome by the way! 

here's my onlydust profile https://app.onlydust.com/u/lauchaves not so much there since I'm starting in this world but here's my git as well https://github.com/lauchaves

**Comment by lindsaymoralesb** [comment]
Hi! @maciejka @MSghais 

My name is Lindsay. I’m a software engineer based in Costa Rica. And I’ve already participated in the past 3 OD hacks with 5 successful contributions to 3 different projects. Feel free to check out my [od-profile](https://app.onlydust.com/u/lindsaymoralesb).

I’m super detail oriented and I also have some experience on the QA field. I’d love to help you with the project testing if there’s still space available for more hands to dive meticulously into the platform!

**Comment by maciejka** [comment]
> Hi! @maciejka @MSghais
> 
> My name is Lindsay. I’m a software engineer based in Costa Rica. And I’ve already participated in the past 3 OD hacks with 5 successful contributions to 3 different projects. Feel free to check out my [od-profile](https://app.onlydust.com/u/lindsaymoralesb).
> 
> I’m super detail oriented and I also have some experience on the QA field. I’d love to help you with the project testing if there’s still space available for more hands to dive meticulously into the platform!

Hi, you need to post your github id on Joyboy to start the testing process.

**Comment by Oshioke-Salaki** [comment]
Hello can I participate?

**Comment by Joy-Adah** [comment]
Hi @maciejka @MSghais I'd love to participate in this.

**Comment by od-hunter** [comment]
JM @maciejka and @MSghais , please can I participate also?

**Comment by Jemiiah** [comment]
JM @maciejka @MSghais i would love to participate

**Comment by NueloSE** [comment]
@maciejka @MSghais i would love to participate in the beta testing

**Comment by bjcd** [comment]
Hey there! Can I participate in the beta testing too? 
21067599

Thanks!

**Comment by No-bodyq** [comment]
Hey @maciejka @MSghais 
I would like to participate as well

**Comment by Megumiiiiii** [comment]
is the follow button didn't enable yet or it just not working?

**Comment by MSghais** [comment]
> Hey @maciejka @MSghais I would like to participate as well 141028690

Can you share also your Github ID with a post on Joyboy, please?
Gonna assign with after this step, thank you we appreciate it!

**Comment by MSghais** [comment]
> 124416278

Hi! Can you send a post on Joyboy with your GitHub ID, please? We are gonna assign you after, thank you

**Comment by petersdt** [comment]
@MSghais @maciejka can i participate on this
168048103

**Comment by MSghais** [comment]
> Is the follow button not enabled yet, or is it just not working?

Thank you for the report! Can you share maybe the process and the issue you encounter?
You can write it on a Doc or an issue on the repo, please

**Comment by Megumiiiiii** [comment]
> > Is the follow button not enabled yet, or is it just not working?
> 
> Thank you for the report! Can you share maybe the process and the issue you encounter? You can write it on a Doc or an issue on the repo, please

https://github.com/keep-starknet-strange/joyboy/issues/229#issue-2421431860

**Comment by syaerulid** [comment]
Hello, @MSghais @maciejka 

I want to participate as well
My Github ID is : 119069839

**Comment by MSghais** [comment]
> Hello can I participate?

With pleasure, can you share your GitHub ID here and on Joyboy, please?

**Comment by syaerulid** [comment]
![image](https://github.com/user-attachments/assets/3f4c4992-c576-4feb-a9f8-5d6709eb57b3)
Can we make some search button, so we can search our friend name / joyboy username and add them easily, menu gonna display dropdown after search

**Comment by martinvibes** [comment]
hello @maciejka  @MSghais 
i will like to participate
my Github ID: 127976766

**Comment by lauchaves** [comment]
JM @maciejka @MSghais, just reported a couple of bugs (prs above) 

I just noticed this icon button is not working as well

![image](https://github.com/user-attachments/assets/ce4dba7e-fac6-4100-ae34-13054221ab2f)

would like to fix it, but I'm not sure if I should make a comment on the current user's profile or just make a post from my profile. Any suggestions?

**Comment by lindsaymoralesb** [comment]
> > Hi! @maciejka @MSghais
> > My name is Lindsay. I’m a software engineer based in Costa Rica. And I’ve already participated in the past 3 OD hacks with 5 successful contributions to 3 different projects. Feel free to check out my [od-profile](https://app.onlydust.com/u/lindsaymoralesb).
> > I’m super detail oriented and I also have some experience on the QA field. I’d love to help you with the project testing if there’s still space available for more hands to dive meticulously into the platform!
> 
> Hi, you need to post your github id on Joyboy to start the testing process.

Hi @maciejka I just posted my id!

**Comment by OkoliEvans** [comment]
hello @maciejka @MSghais 
I will like to participate 
my Github ID: OkoliEvans (ID number not found on my Github profile)

**Comment by MartinXV111** [comment]
> hello @maciejka @MSghais I will like to participate my Github ID: OkoliEvans (ID number not found on my Github profile)

Hey @OkoliEvans can you join the telegram group chat using this link: https://t.me/JoyboyStarknet/1 . We can explain to you how you can get your github ID over there.

**Comment by maciejka** [comment]
>

**Comment by bjcd** [comment]
> Hey there! Can I participate in the beta testing too? 21067599
> 
> Thanks!

fyi - I have lost access to my initial account, creating a new account now.

**Comment by bjcd** [comment]
Here is my first PR. I reported 4 issues that I have identified during the testing.
Let me know if the format is good.

[JoyBoy-bug-report-bjcd.pdf](https://github.com/user-attachments/files/16331913/JoyBoy-bug-report-bjcd.pdf)

**Comment by MullerTheScientist** [comment]
Hello @maciejka @MSghais I will Like to be a part of this project! 
My Github id: 163424834

**Comment by maciejka** [comment]
> Hello @maciejka @MSghais I will Like to be a part of this project! My Github id: 163424834

Sent a message via Joyboy so we can tip you.

**Comment by IamEnergyI** [comment]
I would like participate

**Comment by IamEnergyI** [comment]
I will like to participate 
github id :#80600932

**Comment by IamEnergyI** [comment]
There is no option to logout. makes a user stuck after creating an account. Logout option can be on the user profile page so they can logout and login anytime 
 
![image](https://github.com/user-attachments/assets/d9864f5d-fb60-4cfb-9e0d-90579b0629d5)

**Comment by IamEnergyI** [comment]
I decided to create another and testrun the username code. 
i was able to change my username to a existing account. the new account highlighted in white and the existing account in red. so i can impersonate someone easily since we both can still share same username 
![IMG_1279](https://github.com/user-attachments/assets/261b3a86-7dcc-4e96-a740-f7e65bfee449)

**Comment by maciejka** [comment]
Thanks to all that participated
