### ISSUE TITLE
Follow button not working

### ISSUE THREAD

**Issue by Megumiiiiii** [keep-starknet-strange/joyboy#229]
https://github.com/keep-starknet-strange/joyboy/issues/223#issuecomment-2241613183
As you can see, like button, tip button works perfecly but follow didn't work

https://github.com/user-attachments/assets/d96ece35-e39e-4c35-a158-b7532d3bfa88

**Comment by MSghais** [comment]
Thank you for reporting the issue!

Sorry, but I can't see the Video, can you maybe share some screens?

**Comment by Megumiiiiii** [comment]
how about this, can you play it?

https://abc.megumii.xyz/blog/joy#video

**Comment by Megumiiiiii** [comment]
or maybe it
https://drive.google.com/file/d/1ufCE95oflK0iy4NBtH6sWnu-49hxqgzH/view?usp=sharing
