### ISSUE TITLE
Initialise the mobile application for the Social App

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#23]
# Description

- Init react native pages with OS specific guidelines / practices
- Design UI / UX
- Pages
    - Feed
    - New post
    - Profile

**Comment by ayushtom** [comment]
I can work on this !

**Comment by AbdelStark** [comment]
> I can work on this !

The floor is yours bro!

**Comment by Ugo-X** [comment]
Hello good morning @AbdelStark @maciejka , please can i get the link to the telegram channel?

**Comment by AbdelStark** [comment]
> Hello good morning @AbdelStark @maciejka , please can i get the link to the telegram channel?

https://t.me/JoyboyStarknet
