### ISSUE TITLE
User profile tip button is not working

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#233]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- The Tip button on the user profile is not working 

### Expected

- Tip button triggers tip modal

### Screenshots

Tip button 

![image](https://github.com/user-attachments/assets/347fa80e-8416-4ac8-99da-d2e16894ff0f)

**Comment by MSghais** [comment]
JM! Thank you for reporting the issue, we have fixed it now :)
