### ISSUE TITLE
unable to tip

### ISSUE THREAD

**Issue by adrienlacombe** [keep-starknet-strange/joyboy#236]
Tip failed

index-0fa12e5adebe510d449afd621e4201c7.js:521 [Reanimated] The view with tag -1 is not a valid argument for measure(). This may be because the view is not currently rendered, which may not be a bug (e.g. an off-screen FlatList item).
e.measure @ index-0fa12e5adebe510d449afd621e4201c7.js:521
index-0fa12e5adebe510d449afd621e4201c7.js:1237 Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at W.onAccountsChanged (index-0fa12e5adebe510d449afd621e4201c7.js:1237:18245)
    at index-0fa12e5adebe510d449afd621e4201c7.js:1237:17417
    at inpage.js:1:102855
    at Array.forEach (<anonymous>)
    at ExtStarknetWindowObject.<anonymous> (inpage.js:1:102820)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (inpage.js:1:859044)
    at _next (inpage.js:1:859264)
    at inpage.js:1:859380
    at new Promise (<anonymous>)

**Comment by ugur-eren** [comment]
Hi this warning message is unrelated to your issue with tips

**Comment by adrienlacombe** [comment]
oh ok sorry, then no error in the log I guess...

**Comment by ugur-eren** [comment]
Can you give us some context? What happened? What were you doing? Were you using on sepolia testnet?

**Comment by adrienlacombe** [comment]
I just tried to tip, yes on Sepolia, from desktop using Braavos. Since then tiping is going fine. Should we say it was only a temporary glitch?
