### ISSUE TITLE
Username duplication

### ISSUE THREAD

**Issue by bjcd** [keep-starknet-strange/joyboy#238]
•	Create a new account and choose a given username.
•	Log out
•	Create a new account and choose the same username you have previously created.

Expected behavior: should return: username already used
Actual behavior: twice de same username.
See both public keys with the same username:
•	8a476df0c141fe036683567296fbdae411e941a2cb80efb508c94a49fd369529
•	d05eafd4d628806957b39db70b87a0a906fe218727aabe0bfbe953ca23a7ede8

**Comment by adrianvrj** [comment]
Hi, is this open for collaboration? If so I would like to work on this!

**Comment by ugur-eren** [comment]
Usernames can be duplicated in the nostr. Only NIP-05 usernames can't be duplicates, and we're not using NIP-05
