### ISSUE TITLE
Tipping does not work

### ISSUE THREAD

**Issue by bjcd** [keep-starknet-strange/joyboy#239]
•	Attempt to tip a given user
•	Select ETH amount, click ‘Tip’
•	Argent wallet renders ‘Prediction failure’.
•	Reject transaction.

Reason: wallet was set on mainnet (and sepolia is deprecated on this given account, however), follow these next steps:

•	Try to tip again

Expected behavior: possibility to log in to a new wallet and/or ability to tip after changing network.
Actual behavior: dialog says ‘Failed to send tip’.
<img width="518" alt="Capture d’écran 2024-07-21 à 13 24 12" src="https://github.com/user-attachments/assets/d944c7a3-fc8b-452a-b142-504d166c9626">

**Comment by ugur-eren** [comment]
Rejecting the transaction means, the transaction is failed to sent, and so the tip is failed to sent.
