### ISSUE TITLE
Comments do not work

### ISSUE THREAD

**Issue by bjcd** [keep-starknet-strange/joyboy#240]
•	Open a post
•	Write a comment
•	Click Send

Expected behavior: comment is sent and published
Actual behavior: dialog with ‘error message’.

**Comment by mananbordia** [comment]
I can take a look into this issue. Can someone please assign this to me ?

**Comment by ugur-eren** [comment]
What is the error message you're getting?

**Comment by ugur-eren** [comment]
Closing in favour of #252
