### ISSUE TITLE
Windows 11 - Firefox browser -  Incorrect Alert Message for Import Account button

### ISSUE THREAD

**Issue by MullerTheScientist** [keep-starknet-strange/joyboy#241]
**Steps to Reproduce:**
1. Open the app: https://app.joyboy.community/
2. On the login page
3. Click on the "Import Account" button.
4. Observe the alert message displayed.

**Expected Result:**
The alert message should inform the user that importing an account will add it to their existing accounts, without deleting the current one.
**Actual Result:**
The alert message incorrectly states: "Creating a new account will delete your current account. Are you sure you want to continue?"

**Recommendation:**
Update the alert message for the "Import Account" function to accurately reflect its behavior, such as: "Importing an account will add it to your existing accounts. Continue?" This change will improve the user experience and avoid confusion.

![Screenshot 2024-07-22 101042](https://github.com/user-attachments/assets/7cec2b4a-fb1e-4644-9231-41017490a12c)

**Comment by Immanuelolivia1** [comment]
@MullerTheScientist I will like to work on this

**Comment by ugur-eren** [comment]
This error message is correct, importing or creating will delete the current one.
