### ISSUE TITLE
Windows 11 - Firefox browser -  application’s tipping interface does not display the "Send" button

### ISSUE THREAD

**Issue by MullerTheScientist** [keep-starknet-strange/joyboy#242]
Steps to Reproduce:
1. Open the: https://app.joyboy.community/
2. Click on the Overflow menu (3 dots) located at the bottom of any profile
3. Open the tipping interface on the application.
4. Select "Ether" as the currency for tipping.
5. Enter any amount in the input field.
6. Notice that the "Send" button is not visible.

Expected Behavior:
The application should display a "Send" button that allows users to confirm and complete the transaction after entering the amount.

Actual Behavior:
The "Send" button is not visible on the interface, hindering the user’s ability to proceed with the tipping process.

Recommendation:

1. Inspect the frontend code to ensure that the "Send" button is being rendered correctly.
2. Check for any CSS or JavaScript issues that may be hiding the "Send" button.
3. Verify the button's functionality to ensure it is interactive and triggers the tipping process.
4. Ensure that the UI components, including buttons, are tested across various screen sizes and resolutions to maintain visibility and functionality.

![Screenshot 2024-07-22 113459](https://github.com/user-attachments/assets/a1cce70e-2234-413a-8967-8990c3f6c8ee)

**Comment by Immanuelolivia1** [comment]
I

**Comment by ugur-eren** [comment]
You can scroll down to see the button

**Comment by MullerTheScientist** [comment]
Not at all the scroll is not functional it is stuck
