### ISSUE TITLE
Windows 11 - Firefox browser - Inaccurate Ether (ETH) Transaction Processing

### ISSUE THREAD

**Issue by MullerTheScientist** [keep-starknet-strange/joyboy#243]
Steps to Reproduce:
1. Open the app: https://app.joyboy.community/
2. Click on the overflow menu (3 dots)
3. Open the tipping interface on the application.
4. Select "Ether" as the currency for tipping.
5. Enter any amount in the input field.
6. Observe the displayed message which shows "Sending 7 ETH to @MiracleWeb3Firm".

Expected Behavior
The application should accurately process the entered amount and handle the transaction accordingly.

Actual Behavior
The application displays a message indicating the sending of 7 ETH

Recommendation:
1. Check the code handling the input amount for tipping in Ether.
2. Ensure the backend is processing the entered amount correctly.
3. Verify if the displayed message accurately reflects the transaction being processed.
4. Conduct thorough testing to ensure the issue is resolved.
5. Provide real-time feedback to users as they enter the amount, indicating the exact amount that will be sent and any potential issues.
![second](https://github.com/user-attachments/assets/db13d80a-a48f-4da7-825b-45431b7fc3ee)

**Comment by ugur-eren** [comment]
I don't see the problem here, you've entered 7 ETH, and it shows 7 ETH

**Comment by MullerTheScientist** [comment]
I expected it to show processing not sending.

**Comment by ugur-eren** [comment]
Why should it show "processing" instead of "sending"? I don't get it, sorry..

**Comment by MullerTheScientist** [comment]
I just feel that By using "Processing," the application can provide a more accurate and reassuring user experience, reflecting the true state of the transaction lifecycle.

**Comment by ugur-eren** [comment]
TBH "sending" is just feels right. Sorry, keeping "sending" for now.
