### ISSUE TITLE
 Allows user to view their connections

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#244]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- Connections do not show the user connections

### Expected

- Shows users connections 

### Screenshots

![image](https://github.com/user-attachments/assets/e4c81c87-70dc-4417-8aa2-d8726a9d9de7)

**Comment by ugur-eren** [comment]
Hi, this is not going to be implemented yet unfortunately
