### ISSUE TITLE
Fix Transaction Failure Issue When Tipping Using ArgentX Desktop

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#245]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- When tipping using argentX desktop extension, the transaction fails

### Expected

- transactions succeed, allow tipping 

### Screenshots
![image](https://github.com/user-attachments/assets/e0bf2f51-0a6f-49c1-a52c-8616c1d46196)

![image](https://github.com/user-attachments/assets/85248d7b-87e1-41db-99d9-806e4ea04846)

**Comment by ugur-eren** [comment]
Hi clicking the copy button next to the error message will copy the whole error message. Can you share that?

![resim](https://github.com/user-attachments/assets/c8af4849-4506-4763-b470-63238f70541a)

**Comment by lauchaves** [comment]
hey! @ugur-eren here it is 

`Error in the called contract (0x016d6b7d8ba15d1903ea942a6e9414a70b0f1b2219215dc46faca9a38a522d06):
Error at pc=0:15213:
Got an exception while executing a hint: Requested contract address ContractAddress(PatriciaKey(StarkFelt("0x078a022e6906c83e049a30f7464b939b831ecbe47029480d7e89684f20c8d263"))) is not deployed.
Cairo traceback (most recent call last):
Unknown location (pc=0:222)
Unknown location (pc=0:4845)
Unknown location (pc=0:10647)
Unknown location (pc=0:15231)`

**Comment by ugur-eren** [comment]
Are you trying on the mainnet? Currently only sepolia is supported.

**Comment by ugur-eren** [comment]
This issue can be assigned to contributors who want to implement it.s

There should be a check for connect account's chain id. If the chain is not Starknet Sepolia, app should show a uncloseable dialog with
title: 'Wrong Network'
message: 'Joyboy currently only supports Starknet Sepolia network. Please switch to Sepolia network to continue.'

**Comment by lauchaves** [comment]
got it!, yeah its mainnet 
![image](https://github.com/user-attachments/assets/a40dff7d-fc3e-4583-b1d3-bc13717c1e7f)

**Comment by lauchaves** [comment]
> This issue can be assigned to contributors who want to implement it.s
> 
> There should be a check for connect account's chain id. If the chain is not Starknet Sepolia, app should show a uncloseable dialog with title: 'Wrong Network' message: 'Joyboy currently only supports Starknet Sepolia network. Please switch to Sepolia network to continue.'

@ugur-eren If you agree, I can take care of this 😃

**Comment by lauchaves** [comment]
JM @ugur-eren this is ready for review! Here's the [PR](https://github.com/keep-starknet-strange/joyboy/pull/291)
