### ISSUE TITLE
Adding gifs,images, docs when writing post is not working

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#247]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- Adding gifs,images, docs when writing post is not working

### Expected

- Allows user to add gifs, docs, imgs to posts

### Screenshots

![image](https://github.com/user-attachments/assets/27c570e5-456c-4007-968d-35316aa10768)

**Comment by ugur-eren** [comment]
This feature is not going to be implemented yet unfortunately.
