### ISSUE TITLE
Fix hard coded likes amount

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#248]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- when tipping posts there's some info about the user, and the amount of likes there is hard-coded to 16. 

### Expected

- amount of likes is the same of each post 

### Screenshots

![image](https://github.com/user-attachments/assets/3a941f2b-4fe6-4f6f-8239-88b36d697985)

**Comment by ugur-eren** [comment]
Hi @MSghais can you fix this in your PR too?
