### ISSUE TITLE
Long posts should have the View More feature 

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#249]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- Long posts take a lot of space on the screen, sometimes a lot of scrolling as well

### Expected

- Long posts should have the View More feature 

### Screenshots
![image](https://github.com/user-attachments/assets/10fbe425-4aa5-4af0-b4a3-3e9b96bb60b1)

**Comment by ugur-eren** [comment]
This issue can be assigned to contributors who want to implement it.s

Post content should be sliced after `200` characters and add a text button with `see more...` label should be displayed. Upon clicking the button whole post will be viewed.

**Comment by Bicheka** [comment]
@lauchaves I'll see if I can do something about it

**Comment by lauchaves** [comment]
> This issue can be assigned to contributors who want to implement it.s
> 
> Post content should be sliced after `200` characters and add a text button with `see more...` label should be displayed. Upon clicking the button whole post will be viewed.

@ugur-eren I can work on this as well 🚀

**Comment by lauchaves** [comment]
JM @ugur-eren this is ready for review!  Here's the [PR](https://github.com/keep-starknet-strange/joyboy/pull/290 )
