### ISSUE TITLE
Implement bech32 encoding in Cairo

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#25]
Implement `bech32` encoding:
* spec: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
* sample implementations:
  - https://github.com/sipa/bech32/blob/master/ref/javascript/bech32.js#L86
  - https://github.com/paulmillr/scure-base/blob/main/index.ts#L479

The draft is here: 
https://github.com/keep-starknet-strange/joyboy/blob/main/onchain/src/bech32.cairo

**Comment by Jemiiah** [comment]
@maciejka can I work on this and I will work as soon as possible

**Comment by maciejka** [comment]
Hey @NueloSE, @Jemiiah, nice to meet you.
This issue is on the critical path and rather technically demanding. That is why I don't want to assign it to first time contributors. If you feel it is a good fit for you please provide a pr and if it is promising we will work to get it merged. Does this make sense to you?

P.S.: I  expect this feature to take 2-3 days.

**Comment by okhaimie-dev** [comment]
@maciejka I am working on this right now.

**Comment by maciejka** [comment]
Here is a draft implementation: https://github.com/keep-starknet-strange/joyboy/pull/31
