### ISSUE TITLE
  Alerts/notifications are not working 

### ISSUE THREAD

**Issue by lauchaves** [keep-starknet-strange/joyboy#250]
### Description 

- This is related to [the beta testing ]( https://github.com/keep-starknet-strange/joyboy/issues/223 
)

### Issue 
- Alerts/notifications are not working

### Expected

- Sends notifications about new posts 

### Screenshots
![image](https://github.com/user-attachments/assets/1be39f2e-85c5-4cf6-80ac-c5a4a55bf1d7)

**Comment by ugur-eren** [comment]
Notifications feature is not going to be implemented yet unfortunately
