### ISSUE TITLE
Error message pops up when commenting/long processing time 

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#252]
• Commenting on another person’s post takes long processing time or doesn’t go at all.

• It sometimes gives an error pop up (not network issues of course)
![IMG_6454](https://github.com/user-attachments/assets/fe38b724-5a2e-4a82-808a-ed7c2aa84fd3)

**Comment by ugur-eren** [comment]
Unfortunately I can't re-create this issue. Can you provide some context about the issue?

**Comment by od-hunter** [comment]
I guess you’ve fixed that issue now, I tried commenting under different posts now severally and I didn’t get any error message, but there was an error emoji(provided in the screenshot I sent earlier)
• Now what you should work on now is, making the first comment a person makes under a post remain at the top instead, instead of going down due to another comment. In better words, first come first serve
• For example, a good example is ‘GitHub’ itself, the first person that comments under a post remains at the top and not like it goes down due to other comments.
I’ll provide a short screen record I made.

Should I make this an issue or I can just leave the complain here?

https://github.com/user-attachments/assets/a3919fdc-04b9-499c-82df-a4f991eb0ff0

**Comment by ugur-eren** [comment]
Closing it since it's fixed

**Comment by od-hunter** [comment]
Ok, but you haven’t fixed the second issue which I mentioned. There’s a screen record to explain better.
