### ISSUE TITLE
Fix tipping issues

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#253]
• Unable to tip others on Argent(mobile)

• No way to switch to sepolia on mobile

![IMG_6455](https://github.com/user-attachments/assets/6a4fc737-c6fc-43a0-bf4f-b62d0af19f25)

**Comment by maciejka** [comment]
Testing on mobile does not work on Sepolia right now. It is a matter of Argent wallet on mobile being mainnet only.

**Comment by od-hunter** [comment]
> Testing on mobile does not work on Sepolia right now. It is a matter of Argent wallet on mobile being mainnet only.

What about Braavos? @maciejka
