### ISSUE TITLE
Can’t claim tip on mobile using Braavos option provided

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#255]
• Unable to claim tip on Braavos 
• Says download Braavos(when I already have app in my mobile)
• Refdirected me to a page where I can download the app, open the app but I couldn’t still claim
• Switched to sepolia, I couldn’t still claim

![image](https://github.com/user-attachments/assets/2d59a8c5-0267-4770-b3af-118456b95007)

![image](https://github.com/user-attachments/assets/62e1acf0-bfa6-4cb6-aa1e-2dbd8e763f40)

![image](https://github.com/user-attachments/assets/d66bfed3-9434-40a6-8350-a9d3f4d31411)

![image](https://github.com/user-attachments/assets/fc881fef-50b3-4705-ad2c-8d31515e9b36)

![image](https://github.com/user-attachments/assets/e0c1d499-7357-4fb3-804d-e6c04cb69717)

**Comment by ugur-eren** [comment]
The web app can't connect to the mobile braavos app. This is true for all dapps. What you can do is, open the https://app.joyboy.community through braavos in-app browser.

**Comment by od-hunter** [comment]
@ugur-eren , if so then the option Argent(mobile) shouldn’t be provided. Why provide an option when the user can not make use of it?
Are you saying I can not tip using my device? That is an issue then.

**Comment by od-hunter** [comment]
Please respond @ugur-eren , @maciejka

**Comment by ugur-eren** [comment]
We've removed argent mobile from the available providers list.
Yes, you can't tip using the mobile browser. But you can always use your wallet's in-app browser.

**Comment by od-hunter** [comment]
> We've removed argent mobile from the available providers list. Yes, you can't tip using the mobile browser. But you can always use your wallet's in-app browser.

Noted!
