### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Joy-Adah** [keep-starknet-strange/joyboy#257]
# Bug Report: Joyboy Application

## Mobile Account Claiming Tips and Import Issues

1. **Claiming Tips on Mobile:**

   - **Issue:** When trying to claim my tips on mobile, I encountered an issue where I was unable to claim my tips using my Braavos wallet.
   - **Steps to Reproduce:**
     1. Open Joyboy application on mobile.
     2. Log into your account.
     3. Try to claim tips using Bravoos wallet.
     4. Observe the inability to claim tips due to the fact that there is no Braavos (mobile) option.

![mobile_claim](https://github.com/user-attachments/assets/5c6b2170-e544-4868-9cff-0ee08b20875c)

2. **Desktop Account Import:**

   - **Issue:** I could not import the account I created on mobile to desktop.
   - **Steps to Reproduce:**
     1. Create an account on the mobile application.
     2. Attempt to import the account on the desktop application.
     3. Observe the failure to import.

3. **Warning Message on Account Import:**

   - **Issue:** The message "creating your account will delete my current account" appears when I try to import another account, instead of logging out of the current account.
   - **Steps to Reproduce:**
     1. Log into an account.
     2. Attempt to import another account.
     3. Observe the warning message.

![import_account](https://github.com/user-attachments/assets/f1d8c3dd-1442-43a5-8b7a-4c03c2b38984)

## Profile Update Issues

1. **Profile Information Update:**

   - **Issue:** Error messages "failed to update profile" and "request failed with no response" appear when I tried to update my profile information.
   - **Steps to Reproduce:**
     1. Navigate to profile settings.
     2. Attempt to update profile information.
     3. Observe the error messages.

![update_profile](https://github.com/user-attachments/assets/340f4dfa-64a5-4989-bd86-a438e1c61564)

2. **Profile Picture Update:**

   - **Issue:** The issue persisted even after trying with different profile pictures.
   - **Steps to Reproduce:**
     1. Navigate to profile settings.
     2. Attempt to update profile picture with different images.
     3. Observe the error messages.

![update-profile2](https://github.com/user-attachments/assets/0608871f-102c-480a-9182-dad410c12b27)

## Commenting and Reaction Issues

1. **Comment Posting Delay:**

   - **Issue:** Comments took a while to appear after posting.
   - **Steps to Reproduce:**
     1. Post a comment on any content.
     2. Observe the delay before the comment appears.

![comment](https://github.com/user-attachments/assets/a8b98eb8-3c5d-461d-94bf-3b41fb823d8b)

2. **Reaction (Like) Delay:**
   - **Issue:** Reactions (likes) took a while to appear on comments.
   - **Steps to Reproduce:**
     1. Like a comment.
     2. Observe the delay before the like appears.

## Notification Issues

1. **Comment Notifications:**

   - **Issue:** I did not receive notifications on comments on my posts.
   - **Steps to Reproduce:**
     1. Post content on the Joyboy application.
     2. Have someone comment on the post.
     3. Observe the absence of notifications for the comment.

2. **Reaction Notifications:**
   - **Issue:** I did not receive notifications on reactions (likes) on my posts.
   - **Steps to Reproduce:**
     1. Post content on the Joyboy application.
     2. Have someone react (like) the post.
     3. Observe the absence of notifications for the reaction.

## Icon Functionality Issues

1. **Non-functional Icons:**

   - **Issue:** The Share icon, About icon, and Follow icon are not working.
   - **Steps to Reproduce:**
     1. Click on the Share icon, About icon, or Follow icon.
     2. Observe no action or response.

![share_about_icons](https://github.com/user-attachments/assets/f02b1c3b-7398-4a26-aa6d-1421e387c835)

2. **Tokens Name Buttons Visibility:**

   - **Issue:** Tokens names are not visible until I clicked.
   - **Steps to Reproduce:**
     1. Navigate to the section with token buttons.
     2. Observe the buttons not being visible until clicked.

![token_name_dropdown](https://github.com/user-attachments/assets/393baa3c-c2fc-4ab4-8638-5efbb919d6d5)

## Page Refresh Issues

1. **Page Refresh Logout:**

   - **Issue:** Refreshing the page logs me out and takes me back to the login page.
   - **Steps to Reproduce:**
     1. Log into the Joyboy application.
     2. Refresh the page.
     3. Observe being logged out and redirected to the login page.

![reload](https://github.com/user-attachments/assets/d1b52209-78af-464d-8080-850c2c861705)

## Tip Claiming Issues

1. **Tip Claim Error:**

   - **Issue:** Error prompt "Request failed with no response, please try again later" appears whenever I try to claim tips.
   - **Steps to Reproduce:**
     1. Attempt to claim a tip.
     2. Observe the error prompt.

![claim](https://github.com/user-attachments/assets/a3334d5f-19e6-477c-97f8-e689306f6a7a)

![claim_error](https://github.com/user-attachments/assets/b3dace7c-299a-427d-ac67-04336f5a485d)

2. **Tip Claim Error Code:**

   - **Issue:** Error prompt "Request failed with error code: ESTIMATION_ERROR" appears after trying again. I still have not been able to claim my tips.
   - **Steps to Reproduce:**
     1. Attempt to claim a tip again.
     2. Observe the error code prompt.

![claim_error2](https://github.com/user-attachments/assets/5516ad66-48c6-4dd4-803b-8e567626da92)

![claim_error3](https://github.com/user-attachments/assets/c1430abf-f870-4382-a93d-f3fba2275f86)

## News Feed Issue

1. **Blank Screen on News Feed:**

   - **Issue:** A blank screen appears when clicking on the news feed icon, requiring a page refresh to load the news feed.
   - **Steps to Reproduce:**
     1. Click on the news feed icon.
     2. Observe the blank screen.
     3. Refresh the page to load the news feed.

![blank_screen](https://github.com/user-attachments/assets/32483dbb-4a93-453e-be05-c8319e658725)

![tip_transaction_hash](https://github.com/user-attachments/assets/10c17399-e7b6-4fd1-b841-84a9b8474b64)

![transaction_hash](https://github.com/user-attachments/assets/5c8036b7-57cf-4c21-a8f2-521c1feb9892)

![tip](https://github.com/user-attachments/assets/cef576ba-a550-4b56-ad5c-43670cd63ada)

![github_id_comment](https://github.com/user-attachments/assets/dd24ecf3-c879-43fb-aef7-123178052d6b)

![github_id_comment_joyboy](https://github.com/user-attachments/assets/425d153b-277f-4ab0-86d9-9d429c4d59d2)

![profile](https://github.com/user-attachments/assets/53eda72e-86af-4ef2-bc10-2735c477af97)

**Comment by Joy-Adah** [comment]
Okay. On it

**Comment by ugur-eren** [comment]
Closing this in favour of other issues
