### ISSUE TITLE
Improve Ux experience 

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#258]
•It would be nice if there’s a section on the user profile where the user can see connected wallet.
•Also a User should be able to switch wallets too.

**Comment by ugur-eren** [comment]
The wallet only used during sending the transaction, and the connected account can be switched by changing the account on the connected wallet. Connected wallet can be switched by just simply reloading.

**Comment by od-hunter** [comment]
> The wallet only used during sending the transaction, and the connected account can be switched by changing the account on the connected wallet. Connected wallet can be switched by just simply reloading.

But reloading takes one back to login page sir
