### ISSUE TITLE
Implement nip-19 bech32 encoding of `NostrProfile`

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#26]
nip-19 bech32 encoding of `NostrProfile`:
* spec - https://github.com/nostr-protocol/nips/blob/master/19.md
* sample implementation - https://github.com/nbd-wtf/nostr-tools/blob/master/nip19.ts#L182
* draft: https://github.com/keep-starknet-strange/joyboy/blob/c70fa70affdc911f6b7070bc9989346d520f19f4/onchain/src/nostr_profile.cairo#L19

**Comment by sprtd** [comment]
is this still open

**Comment by maciejka** [comment]
It is already assigned.

**Comment by sprtd** [comment]
Ok, thanks :)
