### ISSUE TITLE
Inability to add Gif or Image file when Creating a post

### ISSUE THREAD

**Issue by martinvibes** [keep-starknet-strange/joyboy#263]
### **User  can't be able to add image or gif**
![gif](https://github.com/user-attachments/assets/11921afb-94a2-45a8-9863-9f9a2a25a657)

https://github.com/user-attachments/assets/90903a28-2ab2-46a2-a2e6-453c3ac0c314

**Comment by ugur-eren** [comment]
Closing in favour of #251
