### ISSUE TITLE
Tip Option Overlaps When Clicking on Three Dots on last User Posts

### ISSUE THREAD

**Issue by martinvibes** [keep-starknet-strange/joyboy#269]
### **when you go to the user profile page and scroll down to the first post made you'll notice that tip option is overlapping when click on the three dot option icon causing the tip option to be unreadable and difficult to select**

**Steps to Reproduce:**

- Log in to the website and navigate to your user profile.
- Scroll down to the last post you made.
- Click on the three dots on the last post to open the options menu.
- Scroll up to the first post you made.
- Click on the three dots on the first post to open the options menu.

**Actual Result:** The options menu overlaps when clicking on the three dots on the first post, causing the options to be unreadable and difficult to select.

**Expected Result:** The options menu should open without overlapping, displaying all options clearly and allowing the user to select them without any visual issues.

![overlap](https://github.com/user-attachments/assets/a86c7747-2cbc-4bac-8012-fa2369a1b7dc)

**Comment by ugur-eren** [comment]
## This issue can be assigned to contributors.

This issue can be simply fixed by adding a second check on the Menu component's display logic. Currently it's only checked for X axis, Y axis should also be added to the check.

**Comment by Oshioke-Salaki** [comment]
Can I do this?

**Comment by martinvibes** [comment]
@ugur-eren I discovered this issue so I can do it
