### ISSUE TITLE
Mobile devices can’t post an image

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#271]
• The image comment feature is available on desktop, but not on my mobile device(I said my mobile device as I don’t know whether other mobile devices can send an image as a comment ).
• Please just notice what I’m saying about not being responsive in my device(notice the way it’s just moving all over the place) It’s not supposed to be so. Kindly fix it.
• Also notice that, when I went back to the homepage/main page the bottom navigation bar was not more there. I raised this up in issue #259 

https://github.com/user-attachments/assets/31c40508-6276-4a75-85bd-3d5639826a61

**Comment by ugur-eren** [comment]
Hi, Images are not supported for comments, it's supported for posts.
As for other responsive issue, we can track that issue in the #259
So i can close this in favour of #259 if i'm not mistaken?

**Comment by od-hunter** [comment]
Not yet, wait let me check if I can post a picture.

**Comment by od-hunter** [comment]
Aha! Just checked. I couldn’t post an image on mobile. Below is a screenshot of the error it gives:
![IMG_6526](https://github.com/user-attachments/assets/a4ae0e40-c387-49a9-afa4-4cf423bbde43)
Should I raise a separate issue for this or I can leave it here?

**Comment by ugur-eren** [comment]
You can leave it here

**Comment by od-hunter** [comment]
Ok sir @ugur-eren
