### ISSUE TITLE
Claiming Tips on Mobile

### ISSUE THREAD

**Issue by Joy-Adah** [keep-starknet-strange/joyboy#272]
Issue: When trying to claim my tips on mobile, I encountered an issue where I was unable to claim my tips using my Braavos wallet.

Steps to Reproduce:

1. Open Joyboy application on mobile.
2. Log into your account.
3. Try to claim tips using Bravoos wallet.
4. Observe the inability to claim tips due to the fact that there is no Braavos (mobile) option.

![mobile_claim](https://github.com/user-attachments/assets/d7f6072c-74a0-45b6-be5b-ddf4c8ce9748)

**Comment by ugur-eren** [comment]
The web app can't connect to the mobile braavos app. This is true for all dapps. What you can do is, open the https://app.joyboy.community through braavos in-app browser.
