### ISSUE TITLE
Warning Message on Account Import

### ISSUE THREAD

**Issue by Joy-Adah** [keep-starknet-strange/joyboy#273]
Issue: The message "creating your account will delete my current account" appears when I try to import another account, instead of logging out of the current account.

Steps to Reproduce:

1. Log into an account.
2. Attempt to import another account.
3. Observe the warning message.

![import_account](https://github.com/user-attachments/assets/12bdbfe1-317e-4d0a-9be3-505a00961ac5)

**Comment by ugur-eren** [comment]
Hi, The warning message is correct, importing an account will remove the current account, if you don't have it's private key, it will be lost forever.
What do you want it to change here?

**Comment by Joy-Adah** [comment]
Thanks for explaining, I understand it better now.
