### ISSUE TITLE
Profile Information Update

### ISSUE THREAD

**Issue by Joy-Adah** [keep-starknet-strange/joyboy#274]
Issue: Error messages "failed to update profile" and "request failed with no response" appear when I tried to update my profile information.

Steps to Reproduce:

1. Navigate to profile settings.
2. Attempt to update profile information.
3. Observe the error messages.

![update_profile](https://github.com/user-attachments/assets/330d4dfb-d969-4493-8295-39edccea7f5f)

**Comment by ugur-eren** [comment]
Is this issue still present? Can you try again if possible?

**Comment by Joy-Adah** [comment]
It has been resolved. Thanks!
