### ISSUE TITLE
Logout option unavailable 

### ISSUE THREAD

**Issue by IamEnergyI** [keep-starknet-strange/joyboy#276]
There is no option to logout. makes a user stuck after creating an account. Logout option can be on the user profile page so they can logout and login anytime
Github: #80600932
![image](https://github.com/user-attachments/assets/739e4232-bafe-4b72-be19-6415733584b7)

**Comment by ugur-eren** [comment]
We didn't implemeted a logout option because, simply closing the tab, or reloading it makes it automatically logout. After that you can login again, or import another account

**Comment by IamEnergyI** [comment]
Alright that is fine
