### ISSUE TITLE
Comment Posting Delay

### ISSUE THREAD

**Issue by Joy-Adah** [keep-starknet-strange/joyboy#277]
Issue: Comments took a while to appear after posting.

Steps to Reproduce:

1. Post a comment on any content.
2. Observe the delay before the comment appears.

![comment](https://github.com/user-attachments/assets/3d31ff4d-52f6-46ae-b90d-9c2ba4765e74)

**Comment by ugur-eren** [comment]
If you didn't do any action for a period of time, the connection to the nostr relay will be closed to save resources. When you do an action, connecting again may take some time.
If there's no other issue other than the delay, i can close this.
