### ISSUE TITLE
Creation of two account with same username 

### ISSUE THREAD

**Issue by IamEnergyI** [keep-starknet-strange/joyboy#278]
I decided to create another and testrun the username code.
i was able to change my username to a existing account. the new account highlighted in white and the existing account in red. so i can impersonate someone easily since we both can still share same username
Github: #80600932

![image](https://github.com/user-attachments/assets/f403f9aa-ebe3-44fd-8483-2a8580a6a7bd)

**Comment by ugur-eren** [comment]
Hi, in Nostr protocol, usernames are not unique. Only NIP-05 usernames are globally unique and unfortunately we don't currently support NIP-05 usernames

**Comment by IamEnergyI** [comment]
do you quite know username are identity to identify a user from another. which that is what works with all socials i know of. so reconsider that
