### ISSUE TITLE
Can’t delete/edit post

### ISSUE THREAD

**Issue by od-hunter** [keep-starknet-strange/joyboy#285]
• Please help. There’s no option provided for me to either delete/edit post/comment
• I saw that I have a duplicate post on the same thing, now I want to delete one and leave the other. Help please
Below is a screenshot to explain better:
![IMG_6528](https://github.com/user-attachments/assets/ae87cd86-c4d2-4bb8-9566-61f3d926db18)

**Comment by ugur-eren** [comment]
Nostr protocol doesn't provide a way to have delete or edit on kind 1 events unfortunately.
This is not a feature we can provide.
