### ISSUE TITLE
Blank post and comments

### ISSUE THREAD

**Issue by lindsaymoralesb** [keep-starknet-strange/joyboy#286]
## Description

Right now the platform doesn't allow a user to post a note if it doesn't have any content, that means blank posts aren't allowed. In the case a person enters just blank spaces the note can be saved. This happens for comments as well.
Related to: #223 

## Solution
Use a trim function before saving the post to make sure it has content.

## Steps to reproduce
1. Click on the new post button
2. Enter just blank spaces
3. Post the note

## Evidence

https://github.com/user-attachments/assets/48b8eda8-ccd3-4b07-847e-94866ad9b9f9

**Comment by lindsaymoralesb** [comment]
Hey! @ugur-eren If this issue is open for contribution I'd like to help.

**Comment by ugur-eren** [comment]
Sure, you can work on it
