### ISSUE TITLE
Request for Implementation of Edit and Delete Comment Feature

### ISSUE THREAD

**Issue by MullerTheScientist** [keep-starknet-strange/joyboy#289]
I would like to propose adding a delete and edit feature to the comment section on Joboy. These features should be positioned either at the top or bottom of each comment for user convenience. Please refer to the attached picture for further clarification.
![Screenshot 2024-07-24 054305](https://github.com/user-attachments/assets/48011b2a-133e-4f64-9167-4601dbf9e0f9)

**Comment by ugur-eren** [comment]
Nostr protocol doesn't provide a way to have delete or edit on kind 1 events unfortunately.
This is not a feature we can provide.
