### ISSUE TITLE
Build issue on Android (Not test on my side in IOS at this moment)

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#45]
I have an issue when trying the app on Mobile Android, my Expo GO app crashed without error for me.
Maybe it's on my side or mobile phone/app.

How to reproduce:
- Go to JoyboyCommunty directory
- Run npm start
- Select your run mode: web, IOS, Android.
- Scan the QR code with the app Expo GO.
- My Expo GO crashed at this stage after the first load of the bundle. I don't receive any errors at this moment to fix it.

We can fix the build issue on Android to finish test the login method.

PS: 
It's maybe a CSS issue on Android like "100%" is not available on this platform like @ayushtom told me.
Also can be a package not accepted in react-native (using node or any other possible issues)

**Comment by ugur-eren** [comment]
Is this issue available to take, or is it part of the upcoming ODHack? I can work on this
