### ISSUE TITLE
Test biometric with react-native-keychain on Android and IOS

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#46]
Related to #45 

Biometrics and passkeys login with react-native-keychain: https://www.npmjs.com/package/react-native-keychain.

After the build fix on Android, we can finish testing and implement the Sign and Login with biometrics.

The implementation is started here: 
https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/modules/login/index.tsx

We can finish testing the implementation, finish it, and refacto if needed.

![image](https://github.com/keep-starknet-strange/joyboy/assets/59928086/60e0deb9-abd5-4159-9d74-8bcaa9a384f8)

UI video: https://t.me/JoyboyStarknet/206/397

**Comment by coxmars** [comment]
Hi @MSghais,

Is this issue still available? I'd like to work on it, I have experience in mobile development with Flutter (Web2).

Thanks!

**Comment by PhantomOz** [comment]
Hello would love to work on this experienced react-native developer

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this, I've worked on some nunbers of ODhacks before
