### ISSUE TITLE
Change `SocialPayAccount` tests not to use snforge  

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#47]
Snforge is not compatible with scarb nighty. It will change soon when Cairo version 2.7 is released. Until then we can't use snforge. 
Please use only pure Cairo for SocialPayAccount test.
There are a lot of tests of this kind in this repo: https://github.com/starknet-io/starkgate-contracts/tree/cairo-1/src/cairo.

**Comment by mubarak23** [comment]
@mubarak23 kindly assign

**Comment by maciejka** [comment]
@mubarak23 how is it going?

**Comment by mubarak23** [comment]
@maciejka Hi 
 i will send a PR today, am solving a version issue with cairo
