### ISSUE TITLE
Implement SocialPay for Sending and Receiving Tips

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/joyboy#5]
## Description
Develop the SocialPay feature that allows users to send and receive tips through Nostr-signed messages, integrating a seamless payment mechanism on our platform.

## Tasks
- [x] #10
- [x] #15
- [x] #11
- [x] #12
- [x] #16
- [x] #97
- [x] #18
- [ ] Extend chatbot from #18 with a handler for transfer requests messages

**Comment by Oshioke-Salaki** [comment]
Please can i have this issue?

**Comment by AbdelStark** [comment]
> Please can i have this issue?

Thanks for your interest. Bare with us few more days please as we will soon announce the project and share the telegram group link to coordinate contributions. Once we do that please manifest again your interest and it will be a pleasure for us to onboard you on this exciting project.

**Comment by aji70** [comment]
i would love to be assigned one of the above tasks

**Comment by maciejka** [comment]
> i would love to be assigned one of the above tasks

Try to snip one when it will become available.

**Comment by Osatuyi** [comment]
@maciejka can I work on the last one.... Extend chatbot from Simple ping pong chatbot.

**Comment by maciejka** [comment]
It is already in the works as part of od hack.
