### ISSUE TITLE
Github actions for Mobile repo

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#52]
GitHub actions & CI/CD for folder /JoyboyCommunity.

- Start implementing Github actions 
- CI/CD check for React-native with Expo

If you can, please update the mobile README for what you do on the Mobile folder.

#45  Build error on Android, I don't get logs for this error crash on Expo GO for Android, and I can't debug easily.

**Comment by bhavyagosai** [comment]
Hey, I can take this up. Can set up the ci cd pipeline and will check the error issue

**Comment by Jemiiah** [comment]
Hey can I work on this

**Comment by MSghais** [comment]
> Hey, I can take this up. Can set up the ci cd pipeline and will check the error issue

Hey,  thank you for the reply! I can assign you to this issue.

Are you available on the Telegram too ? 
Here is the link: https://t.me/JoyboyStarknet

**Comment by MSghais** [comment]
> Hey can I work on this

Hey; this issue is assigned sorry, but we have others issues on mobile too, check the mobile labels! 

Few others are gonna be created soon. 
Contributors definitely welcome.

Btw, are you available on the Telegram?

Here is the link: https://t.me/JoyboyStarknet

**Comment by Jemiiah** [comment]
@MSghais i would be interested in front-end issues if there are or would be in the future
