### ISSUE TITLE
Implement Nostr client that will forward SocialPay requests to Starknet

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#73]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Intro
This task is about prototyping what we call "SocialPay" (btw, better name suggestions are welcome). The idea is to initiate Starknet transactions with Nostr messages. The scenario is as follows:
1. Nostr user, lets call it @bob.foo, using any Nostr client sends an oridinary text message in a predefined format describing a Starknet transaction. For example a message: `@joyboy send 12 USDC to @alice.xyz` would mean: transfer 10 USDC to a Starknet account corresponding to the Nostr user @alice.xyz from a Starknet account corresponding to the sender of the message
2. Bob's client, expands @joyboy.xyz and @alice.xyz mentions into: `nprofile1qys8wumn8ghj7un9d3shjtn2daukymme9e3k7mtdw4hxjare9e3k7mgqyzzxqw6wxqyyqqmv4rxgz2l0ej8zgrqfkuupycuatnwcannad6ayqx7zdcy send 12 USDC to nprofile1qqs2sa3zk4a49umxg4lgvlsaenrqaf33ejkffd78f2cgy4xy38h393s2w22mm`, asks user to sign it and transmits the message to the Nostr relay.
3. A custom Nostr client, which we will call SocialPay Relay, watches messages refering to @joyboy, if the message conforms to a predefined format it will:
   - verify message signature
   - parse it into a representation of a corresponding Cairo struct:  https://github.com/keep-starknet-strange/joyboy/blob/af4ff42f0036739a196a498da5b03933fc3ae16f/onchain/src/social/account.cairo#L20
   - send a transaction to a method `handle_transfer_request` on Bob's account contract. Let's assume we can map Nostr profiles to Starknet accounts somehow. The transaction should be send from relayer's own account. For now  transactions will be sponsored by the relayer. See: https://github.com/keep-starknet-strange/joyboy/blob/af4ff42f0036739a196a498da5b03933fc3ae16f/onchain/src/social/account.cairo#L71 
   - watches transaction progress and sends informational messages to both Bob and Alice.
 ## Architecture
The Nostr relay is ommited here for more clarity.
  ```mermaid
sequenceDiagram
    actor Bob
    actor Alice
    participant SocialPay relay
    participant Starknet Node
    participant Bob Account
    participant STRK Token

    Bob->>SocialPay relay: @joyboy send 10 STRK to @alice
    activate SocialPay relay
    SocialPay relay->>Starknet Node: SocialPay transaction
    Starknet Node->>Bob Account: SocialPay handler
    Bob Account->>STRK Token: transfer
    Starknet Node->>SocialPay relay: SocialPay transaction complete
    SocialPay relay->>Alice: @alice you just recived 10 STRK from @bob
    SocialPay relay->>Bob: @bob transfer of 10 STRK to @alice is complete
    deactivate SocialPay relay
```

## Task
Your job is to implement prototype of SocialPay relay. Prototype should concentrate on executing the flow end to end through all the layers of the system and should not worry about every little detail of the problem. For example it should ignore the question who is supposed to create the accounts. 

## Nonfunctional requirements:
* implementation should be in ts
* research potential sdks, one option is https://github.com/nostr-dev-kit/ndk
* bot should respond to messages like: `nprofile1qys8wumn8ghj7un9d3shjtn2daukymme9e3k7mtdw4hxjare9e3k7mgqyzzxqw6wxqyyqqmv4rxgz2l0ej8zgrqfkuupycuatnwcannad6ayqx7zdcy send 34 USDC to nprofile1qqs2sa3zk4a49umxg4lgvlsaenrqaf33ejkffd78f2cgy4xy38h393s2w22mm`
* provide virtual environment (docker file, docker compose, etc) that will run the SocialPay relay, a local Nostr relay(https://github.com/jimbojw/memorelay) and Starknet devnet
* provide a script that will demonstrate SocialPay interaction
* hint: https://github.com/slaninas/nostr-bot can be used as a reference

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by EjembiEmmanuel** [comment]
D

**Comment by maciejka** [comment]
> @maciejka let me hop on this

Please follow the ODHack guidelines:

> Contributors: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on 
> tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

**Comment by EjembiEmmanuel** [comment]
@maciejka I'd love to work on Cairo or Frontend related issues since this issue is being blocked because of it's complexity.

**Comment by MSghais** [comment]
How I think I can handle this prototyping, let's discuss it please:  
 
Mobile:   
- Create a Utils to check: if a note is SocialPay note based on format: [@joyboy](https://t.me/joyboy) "send" 12 USDC "to" [@alice](https://t.me/alice).xyz
- Utils to find both addresses based on a Nostr handle (details related to NIP-05, NIP-24)  
- Send the event only on the Joyboy Relay 
  
Relay: 
 
- Implement check for SocialPay note with same format  
- Verify the signature of the event 
- Details not be care at this stage: Check if both users have map a Starknet address (I've a proposal for the Cairo side)  
- Create an utils to format a request for SocialPay
- Send and Sign the tx with the signature of the event (who sign, who create account etc, details after, and paymaster)

**Comment by maciejka** [comment]
> Mobile:
> ...
> * Send the event only on the Joyboy Relay

Note that between Bob and SocialPay relay there is a Nostr relay. SocialPay receives oridinary Nostr messages from Bob over Nostr protocol, through a Nostr relay. No need for _any_ client development. I think we already discussed this in a private chat. 

> Relay:
> ...
> * Verify the signature of the event

Don't waste time on verification, we are interested in end to end flow here. Messages will be verified on the smart contract side.
