### ISSUE TITLE
Implement snip-6 for SocialPay account contract 

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#75]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Task
Implement snip-6 for SocialPay account:
* account contract is here: https://github.com/keep-starknet-strange/joyboy/blob/main/onchain/src/social/account.cairo
* it should use bip-340 verification for signature verification: https://github.com/keep-starknet-strange/joyboy/blob/af4ff42f0036739a196a498da5b03933fc3ae16f/onchain/src/bip340.cairo#L149

## References
* https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-6.md

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by No-bodyq** [comment]
Can I hop on this

**Comment by Jemiiah** [comment]
Am I be assigned this

**Comment by jimenezz22** [comment]
Hi @maciejka 
I'm want to take the task of implementing SNIP-6 for the SocialPay account contract. I've reviewed the contract code and I'm confident in my ability to integrate the bip-340 verification for signature verification efficiently.
Estimated Delivery Timeline: Start Date: May 23, 2024, Completion Date: June 1, 2024

**Comment by VictoriaAde** [comment]
Hi, I am Cairo programmer and have a good idea how this would work.
I would like to work on this.

**Comment by mubarak23** [comment]
@maciejka kindly assigned 
Thank you

**Comment by mubarak23** [comment]
from the implementation of SRC6, i need to register our account interface in SRC5 Supported interface

how do i get the our account contract interface Id @maciejka

**Comment by mubarak23** [comment]
as part of this implementation, do i need to implement __validate__ and  __execute__  function

**Comment by mubarak23** [comment]
can you point me to good code implementation of SRC5

**Comment by mubarak23** [comment]
@maciejka does this implementation look similar to what we are going to do on this issue [Argent account contract](https://github.com/argentlabs/argent-contracts-starknet/blob/main/src/account/argent_account.cairo)
