### ISSUE TITLE
Implement snip-5 for SocialPay account contract

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#76]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Task
Implement snip-5 for SocialPay account:
* account contract is here: https://github.com/keep-starknet-strange/joyboy/blob/main/onchain/src/social/account.cairo
* it should use: https://docs.openzeppelin.com/contracts-cairo/0.10.0/introspection

## References
* https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-5.md

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by mubarak23** [comment]
w

**Comment by Jemiiah** [comment]
Znz

**Comment by juandiegocv27** [comment]
d

**Comment by juandiegocv27** [comment]
Hi @maciejka  I would like to take this task as part of ODHack 4.0. I have experience with Cairo and blockchain development, including implementing standards and contracts. Estimated Delivery Timeline: Start Date: May 23, 2024, Completion Date: June 1, 2024. #76

**Comment by VictoriaAde** [comment]
Hi, I am Cairo programmer and have a good idea how this would work.
I would like to work on this.

**Comment by VictoriaAde** [comment]
Thank you for assigning me, I have commenced work on it.
I would give regular updates as I go.

**Comment by VictoriaAde** [comment]
Hi, @maciejka Would I need to write tests? I think I need to as there's no way to be sure the implementation works as expected.

**Comment by maciejka** [comment]
Of course you need to

**Comment by VictoriaAde** [comment]
Alright, noted!

**Comment by VictoriaAde** [comment]
Hi @maciejka, I have written the code and my tests are passing.

I just made a PR now, please let me know if I'm on the right part.
Also, how do I get the interface ID, because I'm currently using a random number as the ID or do you think the interface ID should be added on deployment of the contract?

**Comment by VictoriaAde** [comment]
@maciejka, Here the link to the recorded [video explanation](https://www.loom.com/share/5d4767f69dff4569b371e8adbc3ef6be?sid=c2ca43e9-8273-4441-a7ac-fe4b5cd8aea7) 

For some reason, I can't view my PR anymore.
This keeps blinking.
![image](https://github.com/keep-starknet-strange/joyboy/assets/60205816/b1fdb107-9af3-405c-a3d8-091ea7c682fd)

**Comment by VictoriaAde** [comment]
I can view my PR now.
Do you know what might have gone wrong?

**Comment by maciejka** [comment]
> ment snip-5 for SocialPay account contract . I have experience with Cairo and blockchain development, including implementing standards and contracts. Estima

I can see it: https://github.com/keep-starknet-strange/joyboy/pull/125
