### ISSUE TITLE
Extract social request handling into a component

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#77]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Task
Extract SocialPay features  into a component. Public key should be in stored in the contract body, SocialPay related methods(currently it is just a single function: `handle_transfer_request`) and storage (none at the moment) should be in a separate component.  

## References
* https://github.com/keep-starknet-strange/joyboy/blob/main/onchain/src/social/account.cairo
* https://docs.openzeppelin.com/contracts-cairo/0.8.0/components
* https://book.cairo-lang.org/ch16-02-00-composability-and-components.html

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by Jemiiah** [comment]
m,

**Comment by juandiegocv27** [comment]
z

**Comment by vibenedict** [comment]
Hi, can i jump on this issue

**Comment by danielcdz** [comment]
Hey my name is Daniel I'm from Costa Rica, I have over 3 years as software engineer and I'm making my first steps into blockchain and web3 development, this is my 2nd OD hack and I want to help with this issue is possible!

**Comment by saimeunt** [comment]
Hi @maciejka, I'm an ODHack enthusiast having contributed to multiple cairo repositories in previous editions such as https://github.com/carbonable-labs/cairo-erc-7496 and https://github.com/carbonable-labs/cairo-erc-7498

I'm familiar with Cairo components and would love to refactor the SocialAccount using a SocialPay component.
I will extract the component in a separate file and modify account.cairo to import the component instead.
