### ISSUE TITLE
Research the state of Nostr clients

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#78]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Task
Research the state of Nostr clients. Try to find a Nostr client that just works, which means:
* you can easily open/install it
* it does not stall
* lose you data
* it does not behave in a way that you do not understand. 

The result of the research should have a form of table comparing 3 best mobile and 3 best web and 3 desktop clients and a recommendation which one to use for development and which for everyday use. Part of the task is to present recommended clients on the community call (no more than 20mins) on the 3rd of July. 

## References
* https://nostr.com/clients

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by juandiegocv27** [comment]
z

**Comment by princeibs** [comment]
Can I hop on this issue?

**Comment by Joy-Adah** [comment]
Hi @maciejka can I be assigned this?

**Comment by Ugo-X** [comment]
Hello good evening @maciejka  my name is Ugonna from Nigeria and I am a full-stack developer. I have worked on quite some projects before now, including previous OD hacks. You can check my profile to see my contributions. I am very swift and effective in handling tasks.
Please can I be assigned this issue?

**Comment by od-hunter** [comment]
This is my first time and i'll like to contibute on this @MSghais

**Comment by maciejka** [comment]
Please follow the ODHack guidelines:

> Contributors: Note that we highly recommend that you comment on the issue by introducing yourself and how
> you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks,
> especially if many comment.

**Comment by juandiegocv27** [comment]
sorry about it, im going to fix it @maciejka

**Comment by devcollinss** [comment]
Hello @maciejka,

My name is Collins, and I am a fullstack developer. I'd like to take on this task. Here's my approach:

    Research: Explore the provided list of Nostr clients and additional sources to identify potential clients for comparison.
    Evaluation Criteria: Assess each client based on:
-     Ease of installation
-     Stability
-     Data integrity
-     User-friendliness

    Comparison Table: Create a comparison table for the top 3 clients in each category (mobile, web, and desktop).
    Recommendations: Highlight the best clients for development and everyday use, explaining why they are recommended.

Looking forward to contributing

**Comment by od-hunter** [comment]
Hello @maciejka im a full stack developer with vast knowledge on these things. I need 3 days to complete this project correctly. When I’m assigned this issue, below are the approaches I’d take:

1. Define Evaluation Criteria
2. Identify Nostr Clients
3. Conduct Research
4. Create Comparison Tables
Please this is my first time contributing in Starknet ecosystem and I’d love to be given the opportunity, I promise to deliver with the time frame mentioned below.

**Comment by maciejka** [comment]
@devcollinss @od-hunter how about sharing the issue? You cooperate on defining evaluation criteria, then somehow split the work between you?

**Comment by od-hunter** [comment]
I agree, I will work it out with @devcollinss

**Comment by devcollinss** [comment]
Sure, @od-hunter. Let's work together.

**Comment by maciejka** [comment]
So in the end, it was done by both of you: @od-hunter, @devcollinss?

**Comment by more-of-odeh** [comment]
> So in the end, it was done by both of you: @od-hunter, @devcollinss?

Yes sir

**Comment by od-hunter** [comment]
> So in the end, it was done by both of you: @od-hunter, @devcollinss?

Yes sir.

**Comment by maciejka** [comment]
50/50 split?

**Comment by od-hunter** [comment]
> 50/50 split?

Yes sir

**Comment by devcollinss** [comment]
> 50/50 split?

Yes sir
