### ISSUE TITLE
Try to imagine what you would like Joyboy to become 

### ISSUE THREAD

**Issue by maciejka** [keep-starknet-strange/joyboy#80]
## OD Hack
This issue is part of ODHack 4.0:
* description - https://x.com/OnlyDust_com/status/1791035111992934563
* guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

## Task
Take a few steps back from the screen, close your eyes, it is your hammock time.
![Hammock time!](https://ih1.redbubble.net/image.2594169085.7170/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8.jpg)
In case you don't know what I am talking about, here is a rather lengthy explanation: https://www.youtube.com/watch?v=f84n5oFoZBc&ab_channel=ClojureTV.

Your task is to try to think what is the best direction for Joyboy as a project. Contemplate alternative designs like Farcaster, Lens, etc, try to invent killer features, a master plan, an architecture. Put your thoughts into a short essay. Try to be as specific as possible, don't waffle... 

More than one person/team can work on this one. There should be no more than 10. Submissions will be judged by the project leadership, at most three best will be rewarded and will have the opportunity to present during community call. There might be no rewards is the quality of submissions is to low. 

## References
* https://talk.nervos.org/t/why-nostr-is-important-the-freedom-from-being-governed-by-servers/7538
* https://blog.lopp.net/why-nostr-matters/
* https://docs.lens.xyz/docs/what-is-lens
* https://docs.farcaster.xyz/

## Communication
https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by vibenedict** [comment]
Hi, can i jump on this issue

**Comment by Calebux** [comment]
I worked on the landing page and i have a few ideas on what i want joyboy to be 
i'll like to do this. @maciejka

**Comment by Immanuelolivia1** [comment]
I can work with @Calebux on this if you don't mind @maciejka

**Comment by coxmars** [comment]
Hi @maciejka I would like to be assigned to this issue. I have experience in mobile development and a strong interest in contributing to this project. Here’s my outlook:

- Contemplate potential alternative designs and innovative features for Joyboy.
- Create a detailed plan for Joyboy, focusing on specific, actionable ideas.

Thanks

**Comment by coxmars** [comment]
> Hi @maciejka I would like to help in this issue. I have experience in mobile development and a strong interest in contributing to this project. Here’s my outlook:
> 
> * Contemplate potential alternative designs and innovative features for Joyboy.
> * Create a detailed plan for Joyboy, focusing on specific, actionable ideas.
> 
> Thanks

Link to documentation: https://docs.google.com/document/d/1EtMDNiuy8YLz6Ny9EHUhaPpKKOXOJT9ptZe2XDVEAWs/edit
