### ISSUE TITLE
NIP-10: Components UI for comments with styled-components & Core functionnality to fetch and create comment with NIP-10

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#84]
### OD Hack
This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

### Comments functionality (3 PR distinct)

We can split this issue into 3 PR, everyone can work on one step by step:

NIP-10: UI components + Create a comment + fetch comment for a note

1. Component styled side for comments on Notes based on UI design
2. Core functionally to fetch event tags and IDs for these notes. (WIP)
3. Core event to send create comments. (WIP)

We are working on more documentation and examples for it (PR for it welcome too)

You can learn and start understanding the description of the NIP-10 here:
https://github.com/nostr-protocol/nips/blob/master/10.md

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by Immanuelolivia1** [comment]
I

**Comment by adrianvrj** [comment]
Hi, can I work on one of the prs?

**Comment by EmmanuelAR** [comment]
I can work on the part 3 and @adrianvrj in the 2

**Comment by EmmanuelAR** [comment]
Let's us know @MSghais

**Comment by adrianvrj** [comment]
> I can work on the part 3 and @adrianvrj in the 2

Agree 🤝

**Comment by BlackStarkGoku** [comment]
Hello, I am a React software engineer, and would love to contribute to this project. I have worked a lot with styled-components so I can tackle first PR

**Comment by krshishir1** [comment]
Hey @MSghais, I can work on the 1st part.

**Comment by princeibs** [comment]
Hi, I am a fullstack engineer and I have experience building production react native apps professionallly. I have also worked with teams in the past. I can easily tackle this issue when assigned to me. I also have vast experience writing cairo programs and building on the blockchain as well. This issue is estimated to take two working days for me.

**Comment by od-hunter** [comment]
@MSghais i would love to work on this project please. This is my first time in Starknet ecosystem and will love to proof my acquired skills please, thank you

**Comment by MSghais** [comment]
@BlackStarkGoku PR 1 kindly assigned to you.
Thank you for your detailed comments like the OD hack guidelines, and the brief description we give also on Telegram.
