### ISSUE TITLE
Documentation for Joyboy with Starknet x Nostr

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#85]
### OD Hack
This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

### Documentation

The docs for the implementation, description, vision, proposals, links of docs etc are mainly here on GitHub.

We need to report it on the landing page as another page here:
https://www.joyboy.community

Also, we can think about specific docs for Joyboy. 
We can think if it can be really needed for the vision/business/tech side and if it's needed to work on others' repos for it.

If yes (I think about it for a yes), we can use Docausaurus, because it's easy to use, with a good SEO, docs, and also a blog page.

Discussing it on Telegram: https://t.me/JoyboyStarknet/949

### Communication

Let's sync here for this issue before.

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by vibenedict** [comment]
f

**Comment by Immanuelolivia1** [comment]
i

**Comment by Calebux** [comment]
@MSghais Can i take this up?

**Comment by petersdt** [comment]
@MSghais can i join on this

**Comment by sasasamaes** [comment]
@MSghais I would like to work on this issue.

**Comment by od-hunter** [comment]
@MSghais I do technical documentations, i can handle this

**Comment by No-bodyq** [comment]
@ayushtom can I help with this

**Comment by josephchimebuka** [comment]
Can I handle the docs for implementation and description @MSghais

**Comment by estheroche** [comment]
@MSghais i can take this, kindly assign to me

**Comment by estheroche** [comment]
@MSghais i can take this, kindly assign

**Comment by od-hunter** [comment]
@MSghais I do technical documentations, i can handle this, I'm ready to work

**Comment by krshishir1** [comment]
Hi @MSghais, I have prepared docs using Docausaurus earlier. I would like to work on this!

**Comment by PhavourIB** [comment]
@AbdelStark @maciejka 
I will be working with @Calebux on the design and integration of design components across every point on the website. This is to ensure uniformity and consistency in design style.
