### ISSUE TITLE
FavIcon and Page title

### ISSUE THREAD

**Issue by Shoetan** [keep-starknet-strange/joyboy#88]
![Screenshot 2024-05-23 at 06 46 45](https://github.com/keep-starknet-strange/joyboy/assets/17912134/3b4d66ef-4685-4e16-80b2-d80c7022df76)

Hello Maintainer, I think it will make sense and give a professional feel if the favicon and page title is changed to represent joy community. Attached is a screenshot of what it looks now carrying the default react favicon and page title.

**Comment by Shoetan** [comment]
I would like to work on this if this is a priority. Thanks

**Comment by NueloSE** [comment]
@Shoetan  can i work on this

**Comment by i-hunter** [comment]
I’d love to be assigned this, this is my first time contributing and I would love to be given the opportunity

**Comment by abdegenius** [comment]
I am a fullstack engineer and I will love to handle this issue, Can It be assigned to me..

**Comment by manlikeHB** [comment]
Hi @Shoetan, can I have this issue?

**Comment by Shoetan** [comment]
> Hi @Shoetan, can I have this issue?

@manlikeHB I am so sorry but I am not a maintainer. I only pointed it out and raised an issue.

**Comment by manlikeHB** [comment]
Hi @AbdelStark, I would love to take up this issue.

**Comment by adrianvrj** [comment]
Hi, I would love to work on this issue to introduce myself to this project

**Comment by od-hunter** [comment]
@Shoetan please I will love to work on this project, as this is my first time on Starknet ecosystem and would love to be given the opportunity to proof my skills. Thank you.

**Comment by WebSculptor** [comment]
@Shoetan Hi, let me work on this, real quick

**Comment by Ajith27887** [comment]
@Shoetan Let me work on this

**Comment by ugur-eren** [comment]
Hi @Shoetan , yes you can add the favicon and title. You can use the [logo](https://github.com/keep-starknet-strange/joyboy/tree/main/resources/branding/logo) to generate the favicon.
