### ISSUE TITLE
Figma design: Auth screen

### ISSUE THREAD

**Issue by MSghais** [keep-starknet-strange/joyboy#92]
### OD Hack

This issue is part of ODHack 4.0:

description - https://x.com/OnlyDust_com/status/1791035111992934563
guidelines - https://onlydust.notion.site/ODHack-Common-Guidelines-Project-leads-5e21836f85ad493f9ca429770af0ad40

###  Figma for the new screens

Create new screens using the [Auth module](https://github.com/keep-starknet-strange/joyboy/blob/main/JoyboyCommunity/src/modules/auth/index.tsx) in [screens folder](https://github.com/keep-starknet-strange/joyboy/tree/main/JoyboyCommunity/src/screens/Auth) based on the Figma designs created by @Israelrex9 These new screens should match the designs 1:1

No need for login and create account functionalities, only creating the screens based on the designs is sufficient.

Figma Designs: https://www.figma.com/design/NIJ68MV1AeI8y283woXiM0/JoyBoy?node-id=2-274&t=vCPEMKXnFXuQ3fVJ-0

Required screens are:
- Login
- Create account
- Save your keys

Please battle test it before doing a PR.

### Communication

https://t.me/JoyboyStarknet/949

May the Joy be with you!

**Comment by KodeSage** [comment]
HI

**Comment by princeibs** [comment]
c

**Comment by Shoetan** [comment]
@MSghais Can I be assigned this.

**Comment by adrianvrj** [comment]
Hi! Can I hop on this one?

**Comment by No-bodyq** [comment]
@ayushtom Can I hop on this

**Comment by Ayoazeez26** [comment]
Hi I'm Abdulhakeem, a frontend dev with over 6 years experience in building products and I would love to work on this

**Comment by abdegenius** [comment]
Hi I'm Abijah Johnnie, I love the screen designs. Using components based designs, I will handle this task as swift and fast as possible. @MSghais can you assign this to me. Thank you!

**Comment by BlackStarkGoku** [comment]
Hello, I have been looking at the repo for quite a moment, already installed everything needed to start building on mobile and want to help. I have been looking on videos on Nostr to understand well how It works and can tackle this issue. I am a react engineer

**Comment by WebSculptor** [comment]
Hello, I'm Abdullahi a Frontend developer since 2020, I'd like to work on this

**Comment by josephchimebuka** [comment]
Hello @MSghais I would like the opportunity to handle this. To trust that I can handle it here is something I built previously from figma https://metacrypt.vercel.app/

**Comment by matt-marly** [comment]
Hi, I’m Matthew, a product designer ,and I craft user-centric solutions with pixel-perfect precision. Would love to work on this.

**Comment by Adesooye** [comment]
Hi, I just discovered StarkNet and the wonderful environment it offers. I'm a new contributor and I'm eager to join this project if @MSghais  will allow me. I have years of experience with Figma, so this won't take me much time and it will encourage me to contribute more.

**Comment by Noyi-24-7** [comment]
Hello everyone, nice to meet you @MSghais. I'm Adinoyi, a product and web designer, I enjoy the Nostr topic and I'd love to help out how ever I can. Thanks.

**Comment by ugur-eren** [comment]
Hi @princeibs What's the status of this issue? If you can't continue we have to assign this to someone else before the OD Hack ends

**Comment by princeibs** [comment]
I created a draft PR for the issue. I'll be sending the full PR asap.
